Version: 4
IsBigEndian: False
SupportPaths: False
HasReferenceNodes: False
root:
  !h NetConfig: {!h mPacketStep.s32: !l 2, !h mInetThroughputLimit.s32: !l 12800, !h mLdnThroughputLimit.s32: !l 25600}
